version: '3.3'
services:
    server:
        # restart: always
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        # depends_on:
        #     - postgres
    # postgres:
    #     image: postgres:11
    #     ports:
    #         - "5432:5432"
    #     environment:
    #         POSTGRES_USER=postgres
    #         POSTGRES_PASSWORD=pass
    #         POSTGRES_DB=my_db