version: "3.3"
services:
  server:
    #     # restart: always
    build: .
    ports:
      - "5000"
      - "5001"
    depends_on:
      - postgres
    networks:
      - bridge
  postgres:
    image: postgres:11
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: my_db
    networks:
      - bridge
    volumes:
      - postgresData:/var/lib/postgresql/data
  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: test
      PGADMIN_LISTEN_PORT: 9090
    networks:
      - bridge
    ports:
      - 9091
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - bridge
    depends_on:
      - server
networks:
  bridge:
volumes:
  postgresData:
